### ISSUE TITLE
Keep getting  database must be initialized error

### ISSUE THREAD

**Issue by SemajTheDon** [mpope9/nba-sql#31]
When running the python script I keep getting the database must be initialized error even thought I have created the DB and also changed the settings in the program just seeing if this is something you could possibly help me out with real quick if possible. I attached the feedback I am getting below.  

![Screen Shot 2021-07-25 at 5 02 34 AM](https://user-images.githubusercontent.com/13952039/126893700-366ae80d-58d6-470e-8abc-c5da1443614d.png)

**Comment by avadhanij** [comment]
A bit hard to say since it's MySQL. I use Postgres, and the things I ran into were not creating the user correctly. There has to be a role with the same name, with the create privileges and all. 

Plus, every time I had an issue, I had to drop the database and recreate it.

Did you set all the env variables correctly?

**Comment by mpope9** [comment]
Hi, here is a few things to try:
1. Make sure the database is created: `CREATE DATABASE nba;`
2. Set the proper env vars. You can see the `scripts/create_postgres.sh` script as an example:
```bash
DB_NAME="nba" DB_HOST="localhost" DB_USER=nba_sql DB_PASSWORD=nba_sql python stats/nba_sql.py --create-schema --skip-tables- play_by_play
```

If these don't work I'll create a MySQL docker-compose setup to dig into this.

**Comment by SemajTheDon** [comment]
I have changed the env in setting to my local host and all information that is needed I am still running into this error

**Comment by mpope9** [comment]
@SemajTheDon I'm not sure what your current setup is, but I have tested this on MySQL and I can make a proper connection. I've created this docker-compose file:

```yml
# docker-compose-mysql.yml
version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nba
      MYSQL_USER: nba_sql
      MYSQL_PASSWORD: nba_sql

volumes:
  db_data:
    external: false
```

And the following script:
```bash
# create_mysql.sh
#!/bin/bash

DB_NAME="nba" DB_HOST="localhost" DB_USER=nba_sql DB_PASSWORD=nba_sql python stats/nba_sql.py --create-schema
```

The I started the container with
```bash
docker-compose -f docker-compose-mysql.yml up -d
```

And was able to successfully run the script and load the `team` table. Does your setup resemble this?
